---
- name: Core playbook
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Display variables
      win_shell: Write-Output {{ destination_engineering_db_backup_location }}
