---
- hosts: localhost
  gather_facts: no
  vars_files:
    - vars_temp_${{ github.run_id }}.yml
  tasks:
    - name: Debug Client
      debug:
        msg: "{{ Client }}"
      when: Client is defined

    - name: Debug Environment
      debug:
        msg: "{{ Environment }}"
      when: Environment is defined

    - name: Debug type
      debug:
        msg: "{{ type }}"
      when: type is defined

    - name: Debug Source_Backup
      debug:
        msg: "{{ Source_Backup }}"
      when: Source_Backup is defined

    - name: Debug Destination_Backup
      debug:
        msg: "{{ Destination_Backup }}"
      when: Destination_Backup is defined

    - name: Debug Bypass_Backup
      debug:
        msg: "{{ Bypass_Backup }}"
      when: Bypass_Backup is defined
