---
- name: Main playbook
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    destination_engineering_db_backup_location: 'path_to_backup_location'
  tasks:
    - name: Include Core playbook
      include_tasks: core.yml
      vars:
        destination_engineering_db_backup_location: {{ destination_engineering_db_backup_location }}
