---
- name: Main playbook
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Display variables
      shell: |
        echo "Hello world!"
      register: shell_output
    
    - debug:
        var: shell_output.stdout
