---
- name: Main playbook
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    destination_engineering_db_backup_location: 'path_to_backup_location'
  tasks:
    - name: Set fact
      set_fact:
        destination_engineering_db_backup_location_fact: "{{ destination_engineering_db_backup_location }}"

    - name: Include Core playbook
      include_tasks: core.yml
