---
- name: Main playbook
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    variable1: 'Hello World!'
  tasks:
    - name: Display variables
      shell: echo "{{ variable1 }}"
      register: shell_output
    
    - debug:
        var: shell_output.stdout
