---
- name: Main playbook
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    destination_engineering_db_backup_location: 'path_to_backup_location'
  tasks:
    - name: Include Core playbook
      shell: echo "{{ destination_engineering_db_backup_location }}"
      register: shell_output
    
    - debug:
        var: shell_output.stdout
