name: 'Setup Environment'
description: 'Setup Python and install Ansible'
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Ansible
      run: pip install ansible
      shell: bash
