name: Run Ansible Playbook

on:
  workflow_dispatch:
    inputs: 
      input1:
        description: 'New value for variable 1'     
        required: false
      input2:
        description: 'New value for variable 2'     
        required: false
      input3:
        description: 'New value for variable 3'     
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: Prepare vars file
      run: |
        cp vars.yml vars_temp_${{ github.run_id }}.yml
        if [[ -n "${{ github.event.inputs.input1 }}" ]]; then
          echo "variable1: '${{ github.event.inputs.input1 }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.input2 }}" ]]; then
          echo "variable2: '${{ github.event.inputs.input2 }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.input3 }}" ]]; then
          echo "variable3: '${{ github.event.inputs.input3 }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        
    - name: Print vars_temp.yml
      run: |
        cat vars_temp_${{ github.run_id }}.yml
        echo "Pausing for 30 seconds. Please check the variables and cancel the workflow if needed."
        sleep 30
          
    - name: Run Ansible playbook
      run: ansible-playbook core.yml -e "@vars_temp_${{ github.run_id }}.yml"
