name: Run Ansible Playbook

on:
  workflow_dispatch:
    inputs: 
      Client:
        type: choice
        required: true
        default: 'ALL'
        description: Client
        options:
         - BHAR
         - BHME
         - CMIL
         - LWWA
      Environment:
        type: choice
        required: true
        default: 'ALL'
        description: Environment
        options:
         - ALL
         - PS
         - UAT
         - SBX
      type:
        type: choice
        required: true
        description: Refresh Type
        default: All
        options:
          - Core
          - Portal
          - ALL
      Source_Backup_AppDB:
        description: 'Source_Backup_AppDB'     
        required: false
      Destination_Backup_AppDB:
        description: 'Destination_Backup_AppDB'     
        required: false
      Source_Backup_EngDB:
        description: 'Source_Backup_EngDB'     
        required: false
      Bypass_Backup:
        description: 'Bypass_Backup'
        required: true
        default: 'false'
        type: 'string'
        options: 
         - 'true'
         - 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible
      
    - name: Prepare vars file
      run: |
        cp vars.yml vars_temp_${{ github.run_id }}.yml
        if [[ -n "${{ github.event.inputs.Client }}" ]]; then
          echo "Client: '${{ github.event.inputs.Client }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Environment }}" ]]; then
          echo "Environment: '${{ github.event.inputs.Environment }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.type }}" ]]; then
          echo "type: '${{ github.event.inputs.type }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Source_Backup_AppDB }}" ]]; then
          echo "Source_Backup_AppDB: '${{ github.event.inputs.Source_Backup_AppDB }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Destination_Backup_AppDB }}" ]]; then
          echo "Destination_Backup_AppDB: '${{ github.event.inputs.Destination_Backup_AppDB }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Source_Backup_EngDB }}" ]]; then
          echo "Source_Backup_EngDB: '${{ github.event.inputs.Source_Backup_EngDB }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Bypass_Backup }}" ]]; then
          echo "Bypass_Backup: '${{ github.event.inputs.Bypass_Backup }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        
    - name: Print vars_temp.yml
      run: |
        python3 -c "
        import yaml

        # Load the vars_temp file
        with open('vars_temp_${{ github.run_id }}.yml', 'r') as f:
            vars = yaml.safe_load(f)

        # Print the final values of the keys
        for key, value in vars.items():
            print(f'{key}: {value}')

        print('Pausing for 30 seconds. Please check the variables and cancel the workflow if needed.')
        "
        sleep 30
          
    - name: Run Ansible playbook
      run: ansible-playbook core.yml -e "@vars_temp_${{ github.run_id }}.yml"
