run-name: BHAR REFRESH - ${{ github.event.inputs.my_input }}

on:
  workflow_dispatch:
    inputs:       
      my_input:
        description: 'Input for Ansible playbook'     
        required: true
        default: 'Nil'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Run Ansible playbook without extra vars
      if: github.event.inputs.my_input == 'Nil'
      run: ansible-playbook variable.yml

    - name: Run Ansible playbook with extra vars
      if: github.event.inputs.my_input != 'Nil'
      env:
        MY_INPUT: ${{ github.event.inputs.my_input }}
      run: ansible-playbook variable.yml -e "my_variable='${MY_INPUT}'"
