run-name: ${{ github.event.inputs.Client }} ${{ github.event.inputs.Environment }} REFRESH | ${{ github.event.inputs.type }}

on:
  workflow_dispatch:
    inputs: 
      Client:
        type: choice
        required: true
        default: 'ALL'
        description: Make a choice
        options:
         - BHAR
         - BHME
         - CMIL
         - LWWA
      Environment:
        type: choice
        required: true
        default: 'ALL'
        description: Make a choice
        options:
         - ALL
         - PS
         - UAT
         - SBX
      type:
        type: choice
        required: true
        description: Please choose the refresh type
        default: All
        options:
          - Core
          - Portal
          - All
    
      my_input:
        description: 'Backup Location'     
        required: true
        default: 'Nil'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Run Ansible playbook without extra vars
      if: github.event.inputs.my_input == 'Nil'
      run: ansible-playbook variable.yml

    - name: Run Ansible playbook with extra vars
      if: github.event.inputs.my_input != 'Nil'
      env:
        MY_INPUT: ${{ github.event.inputs.my_input }}
      run: ansible-playbook variable.yml -e "my_variable='${MY_INPUT}'"
