name: Run Ansible Playbook

on:
  workflow_dispatch:
    inputs: 
      Client:
        type: choice
        required: true
        default: 'ALL'
        description: Client
        options:
         - BHAR
         - BHME
         - CMIL
         - LWWA
      Environment:
        type: choice
        required: true
        default: 'ALL'
        description: Environment
        options:
         - ALL
         - PS
         - UAT
         - SBX
      type:
        type: choice
        required: true
        description: Refresh Type
        default: All
        options:
          - Core
          - Portal
          - ALL
      Core_Source_Backup_AppDB:
        description: 'Core_Source_Backup_AppDB'     
        required: false
      Core_Destination_Backup_AppDB:
        description: 'Core_Destination_Backup_AppDB'     
        required: false
      Core_Source_Backup_EngDB:
        description: 'Core_Source_Backup_EngDB'     
        required: false
      Core_Bypass_Backup:
        description: 'Core_Bypass_Backup'
        required: true
        default: 'false'
        type: 'string'
        options: 
         - 'true'
         - 'false'
      Portal_Source_Backup_AppDB:
        description: 'Portal_Source_Backup_AppDB'     
        required: false
      Portal_Destination_Backup_AppDB:
        description: 'Portal_Destination_Backup_AppDB'     
        required: false
      Portal_Source_Backup_EngDB:
        description: 'Portal_Source_Backup_EngDB'     
        required: false
      Portal_Bypass_Backup:
        description: 'Portal_Bypass_Backup'
        required: true
        default: 'false'
        type: 'string'
        options: 
         - 'true'
         - 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible
