name: Run Ansible Playbook

on:
  workflow_dispatch:
    inputs: 
      Client:
        type: choice
        required: true
        default: 'ALL'
        description: Make a choice
        options:
         - BHAR
         - BHME
         - CMIL
         - LWWA
      Environment:
        type: choice
        required: true
        default: 'ALL'
        description: Make a choice
        options:
         - ALL
         - PS
         - UAT
         - SBX
      type:
        type: choice
        required: true
        description: Please choose the refresh type
        default: All
        options:
          - Core
          - Portal
          - ALL
      Source_Backup [App DB]:
        description: 'New value for variable 1'     
        required: false
      Destination_Backup [App DB]:
        description: 'New value for variable 2'     
        required: false
      Source_Backup [Eng DB]:
        description: 'New value for variable 3'     
        required: false
      Bypass_Backup:
        type: choice
        required: true
        description: DO you want to Skip the backup?
        default: No
        options:
          - Yes
          - No

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible
      
    - name: Prepare vars file
      run: |
        cp vars.yml vars_temp_${{ github.run_id }}.yml
        if [[ -n "${{ github.event.inputs.Client }}" ]]; then
          echo "Client: '${{ github.event.inputs.Client }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Environment }}" ]]; then
          echo "Environment: '${{ github.event.inputs.Environment }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.type }}" ]]; then
          echo "type: '${{ github.event.inputs.type }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Source_Backup }}" ]]; then
          echo "Source_Backup: '${{ github.event.inputs.Source_Backup }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Destination_Backup }}" ]]; then
          echo "Destination_Backup: '${{ github.event.inputs.Destination_Backup }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Source_Backup }}" ]]; then
          echo "Source_Backup: '${{ github.event.inputs.Source_Backup }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        if [[ -n "${{ github.event.inputs.Bypass_Backup }}" ]]; then
          echo "Bypass_Backup: '${{ github.event.inputs.Bypass_Backup }}'" >> vars_temp_${{ github.run_id }}.yml
        fi
        
    - name: Print vars_temp.yml
      run: |
        cat vars_temp_${{ github.run_id }}.yml
        echo "Pausing for 30 seconds. Please check the variables and cancel the workflow if needed."
        sleep 30
          
    - name: Run Ansible playbook
      run: ansible-playbook core.yml -e "@vars_temp_${{ github.run_id }}.yml"
